### PR TITLE
playerindicators: fix agility icon spacing

### LINKED ISSUE #1516: PlayerIndicators: Agility icon is jammed right up next to the level and looks bad
**To Reproduce**
1. Enable player indicators
2. Enable show combat level
3. Enable show agility
4. As icons

**Expected behavior**
Better arrangement

**Screenshots**
image

image

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

### PR DESCRIPTION
**Pull request by Damhan**
closes #1516 
Added a spacer of 10px if combat level is enabled to prevent the icon being squished.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java [hunk 1]
```diff
@@ -160,7 +160,17 @@ private void drawSceneOverlays(Graphics2D graphics, Player actor, PlayerRelation
 
 			if (plugin.getAgilityFormat() == PlayerIndicatorsPlugin.AgilityFormats.ICONS)
 			{
-				final int width = graphics.getFontMetrics().stringWidth(name);
+
+				final int width;
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java]:
```java
final int width = plugin.isShowCombatLevel() ? graphics.getFontMetrics().stringWidth(name) + 10 : graphics.getFontMetrics().stringWidth(name);
```
does the exact same thing
