### PR TITLE
npcunaggroarea: Local Player NPE Fix

### LINKED ISSUE #1338: npcunaggroarea: NullPointerException
```java
2019-08-15 10:18:21 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.NullPointerException
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.isNpcMatch(NpcAggroAreaPlugin.java:310)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.checkAreaNpcs(NpcAggroAreaPlugin.java:338)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.recheckActive(NpcAggroAreaPlugin.java:351)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.onGameStateChanged(NpcAggroAreaPlugin.java:504)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
	at net.runelite.client.callback.Hooks.post(Hooks.java:159)
	at client.gameStateChanged(client.java:1057)
	at cv.ei(cv.java:1105)
	at client.ea(client.java:2075)
	at client.ad(client.java:922)
	at bz.j(bz.java:364)
	at bz.run(bz.java:343)
	at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by Netami1**
Added null check for local player and guard case #1338 

closes #1338

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java [hunk 1]
```diff
@@ -307,7 +307,13 @@ private boolean isNpcMatch(NPC npc)
 
 		// Most NPCs stop aggroing when the player has more than double
 		// its combat level.
-		int playerLvl = client.getLocalPlayer().getCombatLevel();
+		Player localPlayer = client.getLocalPlayer();
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java]: final

File: runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java [hunk 2]
```diff
@@ -307,7 +307,13 @@ private boolean isNpcMatch(NPC npc)
...
+		if (localPlayer == null)
+		{
+			return false;
+		}
+
+		int playerLvl = localPlayer.getCombatLevel();
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java]: final

File: runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java [hunk 3]
```diff
@@ -307,7 +307,13 @@ private boolean isNpcMatch(NPC npc)
...
 		int npcLvl = composition.getCombatLevel();
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java]: final

File: runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java [hunk 4]
```diff
@@ -307,7 +307,13 @@ private boolean isNpcMatch(NPC npc)
...
 		String npcName = composition.getName().toLowerCase();
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java]: final
