### PR TITLE
coxhelper: fix teleport timers for names with spaces

### LINKED ISSUE #1626: Cox: name with spaces break teleport timer
**Describe the bug**
The teleport timer doesn't appear on players with space in their name.

**To Reproduce**
Enable cox helper with teleports help
go to olm with someone that has a space in their name.

**Expected behavior**
No timer shows.

### PR DESCRIPTION
**Pull request by Netami1**
sanitize player name for non-breaking spaces
add null check player name

closes #1626

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java [hunk 1]
```diff
@@ -217,9 +217,16 @@ private void onChatMessage(ChatMessage event)
 			{
 				for (Player player : client.getPlayers())
 				{
-					if (player.getName().equals(tpMatcher.group(1)))
+					final String rawPlayerName = player.getName();
+
+					if (rawPlayerName != null)
 					{
-						victims.add(new Victim(player, Victim.Type.TELEPORT));
+						final String fixedPlayerName = Text.sanitize(rawPlayerName);
```
Comment (Ganom) [inline runelite-client/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java]: Text.sanitize just removes images from names, for instance, the hardcore ironman symbol when someone talks. A better option would be text.standardize, or text.toJagexName
